### ISSUE TITLE
Leaving queue notifies buyer that someone has left the queue

### ISSUE THREAD

**Issue by andrewzulaybar** [narendrasss/messaging#69]
Current functionality:
[BUYER]: Leave queue
[BOT]: You have successfully been removed from the queue.
[BOT]: Someone from one of the listings you're watching has left the queue.
[BOT]: You're first in line for <title>.

Expected functionality:
[BUYER]: Leave queue
[BOT]: You have been successfully removed from the queue.

**Comment by narendrasss** [comment]
I just fixed this LOL

**Comment by andrewzulaybar** [comment]
@narendrasss OKAY YA I JUST REALIZED HAHA
